git rm -f CddBdrv
git rm -f EcuabCanIf
git rm -f EcuabCryIf
git rm -f EcuabEa
git rm -f EcuabEthIf
git rm -f EcuabFee
git rm -f EcuabFrIf
git rm -f EcuabFrTp
git rm -f EcuabJ1939Tp
git rm -f EcuabLinIf
git rm -f EcuabLinTp
git rm -f EcuabMemIf
git rm -f EcuabWdgIf
git rm -f McalAdc
git rm -f McalCan
git rm -f McalCry
git rm -f McalDio
git rm -f McalEep
git rm -f McalEth
git rm -f McalFls
git rm -f McalFr
git rm -f McalGpt
git rm -f McalIcu
git rm -f McalLin
git rm -f McalMcu
git rm -f McalOcu
git rm -f McalPort
git rm -f McalPwm
git rm -f McalSpi
git rm -f McalWdg
git rm -f ProjectARA
git rm -f ProjectCfg
git rm -f ProjectCompiler
git rm -f ProjectConst
git rm -f ReSimCmd
git rm -f ReSimFm
git rm -f SwcApplFoc
git rm -f SwcServiceBswM
git rm -f SwcServiceCanNm
git rm -f SwcServiceCanSm
git rm -f SwcServiceCanTp
git rm -f SwcServiceCom
git rm -f SwcServiceComM
git rm -f SwcServiceCsm
git rm -f SwcServiceDcm
git rm -f SwcServiceDem
git rm -f SwcServiceDet
git rm -f SwcServiceDlt
git rm -f SwcServiceEcuM
git rm -f SwcServiceFiM
git rm -f SwcServiceFrNm
git rm -f SwcServiceIoHwAb
git rm -f SwcServiceIpduM
git rm -f SwcServiceNm
git rm -f SwcServiceNvM
git rm -f SwcServiceOs
git rm -f SwcServicePduR
git rm -f SwcServiceSchM
git rm -f SwcServiceSecOC
git rm -f SwcServiceSokFm
git rm -f SwcServiceStartUp
git rm -f SwcServiceStbM
git rm -f SwcServiceVkms
git rm -f SwcServiceWdgM
git rm -f common
