git submodule add https://github.com/NagarajaHuliyapuradaMata/CddBdrv.git CddBdrv
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabCanIf.git EcuabCanIf
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabCryIf.git EcuabCryIf
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabEa.git EcuabEa
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabEthIf.git EcuabEthIf
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabFee.git EcuabFee
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabFrIf.git EcuabFrIf
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabFrTp.git EcuabFrTp
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabJ1939Tp.git EcuabJ1939Tp
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabLinIf.git EcuabLinIf
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabLinTp.git EcuabLinTp
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabMemIf.git EcuabMemIf
git submodule add https://github.com/NagarajaHuliyapuradaMata/EcuabWdgIf.git EcuabWdgIf
git submodule add https://github.com/NagarajaHuliyapuradaMata/LibAutosar.git LibAutosar
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalAdc.git McalAdc
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalCan.git McalCan
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalCry.git McalCry
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalDio.git McalDio
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalEep.git McalEep
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalEth.git McalEth
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalFls.git McalFls
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalFr.git McalFr
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalGpt.git McalGpt
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalIcu.git McalIcu
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalLin.git McalLin
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalMcu.git McalMcu
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalOcu.git McalOcu
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalPort.git McalPort
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalPwm.git McalPwm
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalSpi.git McalSpi
git submodule add https://github.com/NagarajaHuliyapuradaMata/McalWdg.git McalWdg
git submodule add https://github.com/NagarajaHuliyapuradaMata/ProjectARA.git ProjectARA
git submodule add https://github.com/NagarajaHuliyapuradaMata/ProjectCfg.git ProjectCfg
git submodule add https://github.com/NagarajaHuliyapuradaMata/ProjectCompiler.git ProjectCompiler
git submodule add https://github.com/NagarajaHuliyapuradaMata/ProjectConst.git ProjectConst
git submodule add https://github.com/NagarajaHuliyapuradaMata/ReSimCmd.git ReSimCmd
git submodule add https://github.com/NagarajaHuliyapuradaMata/ReSimFm.git ReSimFm
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcApplFoc.git SwcApplFoc
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceBswM.git SwcServiceBswM
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceCanNm.git SwcServiceCanNm
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceCanSm.git SwcServiceCanSm
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceCanTp.git SwcServiceCanTp
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceCom.git SwcServiceCom
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceComM.git SwcServiceComM
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceCsm.git SwcServiceCsm
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceDcm.git SwcServiceDcm
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceDem.git SwcServiceDem
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceDet.git SwcServiceDet
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceDlt.git SwcServiceDlt
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceEcuM.git SwcServiceEcuM
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceFiM.git SwcServiceFiM
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceFrNm.git SwcServiceFrNm
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceIoHwAb.git SwcServiceIoHwAb
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceIpduM.git SwcServiceIpduM
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceNm.git SwcServiceNm
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceNvM.git SwcServiceNvM
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceOs.git SwcServiceOs
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServicePduR.git SwcServicePduR
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceSchM.git SwcServiceSchM
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceSecOC.git SwcServiceSecOC
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceSokFm.git SwcServiceSokFm
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceStartUp.git SwcServiceStartUp
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceStbM.git SwcServiceStbM
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceVkms.git SwcServiceVkms
git submodule add https://github.com/NagarajaHuliyapuradaMata/SwcServiceWdgM.git SwcServiceWdgM
git submodule add https://github.com/NagarajaHuliyapuradaMata/common.git common

