#ifndef HUF_DIAG_HEADER_
#define HUF_DIAG_HEADER_

typedef enum TPMSDiagnosticRequest{
      E_TPMS_DIAG_READ_WS_ID1
   ,  E_TPMS_DIAG_READ_WS_ID2
   ,  E_TPMS_DIAG_READ_WS_ID3
   ,  E_TPMS_DIAG_READ_WS_ID4
   ,  E_TPMS_DIAG_READ_ID_FL
   ,  E_TPMS_DIAG_READ_ID_FR
   ,  E_TPMS_DIAG_READ_ID_RR
   ,  E_TPMS_DIAG_READ_ID_RL
   ,  E_TPMS_DIAG_READ_LAST_RECEIVED_WS
   ,  E_TPMS_DIAG_WRITE_WS_ID1
   ,  E_TPMS_DIAG_WRITE_WS_ID2
   ,  E_TPMS_DIAG_WRITE_WS_ID3
   ,  E_TPMS_DIAG_WRITE_WS_ID4
   ,  E_TPMS_DIAG_READ_WS_IDS
   ,  E_TPMS_DIAG_WRITE_WS_IDS
   ,  E_TPMS_DIAG_READ_SPECIFIC_PARAMETERS
   ,  E_TPMS_DIAG_WRITE_SPECIFIC_PARAMETERS
   ,  E_TPMS_DIAG_READ_AUTO_LEARN_WS_PARAMETERS
   ,  E_TPMS_DIAG_WRITE_AUTO_LEARN_WS_PARAMETERS
   ,  E_TPMS_DIAG_READ_PRESSURE_OF_MIN_PRESS
   ,  E_TPMS_DIAG_WRITE_PRESSURE_OF_MIN_PRESS
   ,  E_TPMS_DIAG_START_TPMS_EOL
   ,  E_TPMS_DIAG_STOP_TPMS_EOL
   ,  E_TPMS_DIAG_RESULT_TPMS_EOL
   ,  E_TPMS_DIAG_READ_ECU_FAULT_REASON
   ,  E_TPMS_DIAG_WRITE_ECU_FAULT_REASON
   ,  E_TPMS_DIAG_READ_ECU_POSITION
   ,  E_TPMS_DIAG_WRITE_ECU_POSITION
   ,  E_TPMS_DIAG_READ_ABS_TICKS
   ,  E_TPMS_DIAG_WRITE_ABS_TICKS
   ,  E_TPMS_DIAG_READ_NOISE_LEVEL
   ,  E_TPMS_DIAG_WRITE_NOISE_LEVEL
   ,  E_TPMS_DIAG_READ_TEMPERATURE_WARNING_THR
   ,  E_TPMS_DIAG_WRITE_TEMPERATURE_WARNING_THR
   ,  E_TPMS_DIAG_MAX_NUMBER
}enum_TPMSDiagnosticRequest;

typedef struct{
   uint8*  pucReqData;
   uint16  uiReqDataLen;
   uint8*  pucResData;
   uint16* puiResDataLen;
}tsTPMSDiag_Data;

extern uint8 infSwcApplTpmsSwcServiceDcm_u8Callback(
   const enum_TPMSDiagnosticRequest eDiagRequest,
         tsTPMSDiag_Data*           PS_MsgContext
);

#endif

